### ISSUE TITLE
'title'/'honorifics' in employee model

### ISSUE THREAD

**Issue by RonMen** [prismify/oc-hrm-plugin#2]
Hi,

it would be very usefull to extend the employee model with 'title'/'honorifics', to set up employees with something like "Phd. Dr. ..." or "Professor ...".

Regards
RonMen

**Comment by algoriq** [comment]
Fixed in afc90e5c6030dfbcf27b563d7b1d5c83d5514192

**Comment by algoriq** [comment]
Fixed in afc90e5c6030dfbcf27b563d7b1d5c83d5514192
