### ISSUE TITLE
Add support for translation to RFC3966 compliant phone number formater in component

### ISSUE THREAD

**Issue by RonMen** [prismify/oc-hrm-plugin#5]
Hi,

it would be nice to have a twig function to render phone numbers (eg. "+49 (0) 12 34 56 78") into RFC3966 compliant phone numbers to be used as "tel:" links in templates.

I think a library like https://github.com/Propaganistas/Laravel-Phone would be nice.

Regards
RonMen

**Comment by algoriq** [comment]
Research and testing is required for this issue request.
